### ISSUE TITLE
npm ERR! time@0.12.0 install: `node-gyp rebuild` on windows server2012r2

### ISSUE THREAD

**Issue by sandrija** [TooTallNate/node-time#104]
Hi everyone,

I am getting error when trying to install npm time on windows server2012r2.

All enviroment variables are added in path, tested with other projects.

Can any one help me?

`C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\node_modules\time>i
f not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\np
m\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
 (node "" rebuild )
Build started 6/21/2017 9:40:54 AM.
__________________________________________________
Project "C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\node_modul
es\time\build\binding.sln" (default targets):

Target ValidateSolutionConfiguration:
    Building solution configuration "Release|x64".
Target Build:
    Target time:
        C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\node_module
s\time\build\binding.sln : error MSB3428: Could not load the Visual C++ componen
t "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install
Microsoft Visual Studio 2005 or 3) add the location of the component to the syst
em path if it is installed elsewhere.
    Done building target "time" in project "binding.sln" -- FAILED.
Done building target "Build" in project "binding.sln" -- FAILED.

Done building project "binding.sln" -- FAILED.

Build FAILED.
C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\node_modules\time\b
uild\binding.sln : error MSB3428: Could not load the Visual C++ component "VCBui
ld.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsof
t Visual Studio 2005 or 3) add the location of the component to the system path
if it is installed elsewhere.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.04
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\node_m
odules\time
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "time"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! time@0.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the time@0.12.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\flash-clean\flashpaper-server\npm-de
bug.log```

**Comment by Qwerty1Verified** [comment]
Did you ever fix this? I use NPM with other projects but all of a sudden on this one project it's giving me issues
