### ISSUE TITLE
Doesn't install on iojs (OSX)

### ISSUE THREAD

**Issue by medikoo** [TooTallNate/node-time#65]
```
$ npm install time
-
> time@0.11.0 install /Users/medikoo/Projects/_tests/time/node_modules/time
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/time/src/time.o
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:616:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/medikoo/.node-gyp/1.0.3/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:615:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:610:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1973:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/medikoo/.node-gyp/1.0.3/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1974:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/medikoo/.node-gyp/1.0.3/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1975:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/medikoo/.node-gyp/1.0.3/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1975:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1976:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/time/src/time.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/medikoo/.nvm/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/medikoo/.nvm/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/medikoo/Projects/_tests/time/node_modules/time
gyp ERR! node -v v1.0.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/medikoo/.nvm/versions/io.js/v1.0.3/bin/iojs" "/Users/medikoo/.nvm/versions/io.js/v1.0.3/bin/npm" "install" "time"
npm ERR! node v1.0.3
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE

npm ERR! time@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/medikoo/Projects/_tests/time/npm-debug.log
```

**Comment by medikoo** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by medikoo** [comment]
Any feedback on that? Is this project still maintained?

**Comment by pauliusuza** [comment]
+1 does not work for us with iojs

**Comment by TooTallNate** [comment]
Probably just need to bump the `nan` version number. I'll take a PR!

**Comment by nkcmr** [comment]
@TooTallNate I bumped `nan` to `1.4.3` and it will compile, but one test is failing:
```
 1) Date #setTimezone() relative should calculate correctly when UTC date is day before timezone date:
     AssertionError: 'Fri Feb 01 2013 02:47:01 GMT+1100 (AEDT)' == 'Fri Feb 01 2013 02:47:01 GMT+1100 (EST)'
      at Context.<anonymous> (/Users/nkcmr/projects/node-time/test/date.js:232:16)
      at callFn (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:374:10)
      at /Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:299:14)
      at /Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/nkcmr/projects/node-time/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by medikoo** [comment]
@TooTallNate it's not just about bumping nan version number. It just doesn't compile, even with latest nan (v.1.6.2) onboard. See what happens:

```javascript
> time@0.11.0 install /Users/medikoo/Projects/eregistrations/lomas/node_modules/time
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/time/src/time.o
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:616:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/medikoo/.node-gyp/1.1.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:615:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:610:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1973:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/medikoo/.node-gyp/1.1.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1974:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/medikoo/.node-gyp/1.1.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1975:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/medikoo/.node-gyp/1.1.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/time.cc:7:
../node_modules/nan/nan.h:1975:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1976:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/time/src/time.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/medikoo/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/medikoo/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/medikoo/Projects/eregistrations/lomas/node_modules/time
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/medikoo/.nvm/versions/io.js/v1.1.0/bin/iojs" "/Users/medikoo/.nvm/versions/io.js/v1.1.0/bin/npm" "rebuild"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
npm ERR! time@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/medikoo/Projects/eregistrations/lomas/npm-debug.log
```

I would be very happy to provide a pull request, but I'm totally not C++ person.

**Comment by hmalphettes** [comment]
@medikoo here is a PR to fix the compilation errors with the latest NaN: https://github.com/TooTallNate/node-time/pull/66

Found the solution to the compilation errors here: https://github.com/rvagg/nan/issues/233#issuecomment-70076024

We still have the failing test reported by @nkcmr https://github.com/TooTallNate/node-time/issues/65#issuecomment-73411243

**Comment by hmalphettes** [comment]
@nkcmr the test failure is also present on node-0.10.
I dont think it is related to NaN. Here is a PR to fix it: https://github.com/TooTallNate/node-time/pull/67

**Comment by hmalphettes** [comment]
@medikoo it is all merged and node-time-0.11.1 works for me.

**Comment by TooTallNate** [comment]
w00t!

**Comment by medikoo** [comment]
Thank you!!
