### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by mudaser-caremerge** [TooTallNate/node-time#69]
Hi,

i am getting following error while install the node app

```
SMAKs-MacBook-Pro:hfp-node smak$ npm install time
\
> time@0.10.0 install /Users/smak/vagrant/careaxiom/hfp-node/node_modules/time
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/time/src/time.o
In file included from ../src/time.cc:7:
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:261:12: error: no member named 'New' in 'v8::String'
   return  _NAN_ERROR(v8::Exception::Error, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:265:5: error: no member named 'ThrowException' in namespace
      'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:265:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:270:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:276:65: error: no member named 'New' in 'v8::String'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:278:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:289:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:293:5: error: no member named 'ThrowException' in namespace
      'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:293:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:297:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:301:5: error: no member named 'ThrowException' in namespace
      'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:301:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:257:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:544:49: error: too few arguments to function call, single
      argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/smak/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../src/time.cc:7:
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:545:14: error: no member named 'NewSymbol' in 'v8::String'; did
      you mean 'IsSymbol'?
    obj->Set(NanSymbol("callback"), fn);
             ^~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:141:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/smak/.node-gyp/0.12.0/deps/v8/include/v8.h:1379:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
In file included from ../src/time.cc:7:
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:545:14: error: call to non-static member function without an
      object argument
    obj->Set(NanSymbol("callback"), fn);
             ^~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:141:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:551:12: error: no member named 'Dispose' in
      'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Dispose();
    ~~~~~~ ^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:552:12: error: no member named 'Clear' in
      'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Clear();
    ~~~~~~ ^
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:556:46: error: no member named 'NewSymbol' in 'v8::String'; did
      you mean 'IsSymbol'?
    return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                             ^~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:141:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/smak/.node-gyp/0.12.0/deps/v8/include/v8.h:1379:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
In file included from ../src/time.cc:7:
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:556:46: error: call to non-static member function without an
      object argument
    return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                             ^~~~~~~~~~~~~~~~~~~~~
/Users/smak/vagrant/careaxiom/hfp-node/node_modules/time/node_modules/nan/nan.h:141:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/time/src/time.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/smak/vagrant/careaxiom/hfp-node/node_modules/time
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "time"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! time@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.10.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/smak/vagrant/careaxiom/hfp-node/npm-debug.log

```

Can you please help me?

**Comment by Stono** [comment]
same, take it you dont support 0.12?

**Comment by TooTallNate** [comment]
Can you guys try time v0.11.2?

**Comment by ruddct** [comment]
0.11.2 works for me. I've been seeing these same errors on both AWS Ubuntu and OSX with Node 0.12

**Comment by DenisIzmaylov** [comment]
Have the same troubles in with Node 12
