### ISSUE TITLE
    npm ERR! Failed at the time@0.11.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by paulomcnally** [TooTallNate/node-time#74]
azureuser@dak42-cron:~/chacuatool-news-cron$ npm install
    npm WARN package.json chacuatool-news-cron@0.0.1 No description
    npm WARN package.json chacuatool-news-cron@0.0.1 No README data
    npm WARN package.json chacuatool-news-cron@0.0.1 homepage field must start with a protocol.
    -
    > time@0.11.3 install /home/azureuser/chacuatool-news-cron/node_modules/time
    > node-gyp rebuild
    
    gyp ERR! build error 
    gyp ERR! stack Error: not found: make
    gyp ERR! stack     at F (/home/azureuser/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/which/which.js:72:28)
    gyp ERR! stack     at E (/home/azureuser/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/which/which.js:75:29)
    gyp ERR! stack     at /home/azureuser/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/which/which.js:83:16
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
    gyp ERR! System Linux 3.19.0-18-generic
    gyp ERR! command "node" "/home/azureuser/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/azureuser/chacuatool-news-cron/node_modules/time
    gyp ERR! node -v v0.12.4
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok 
    npm ERR! Linux 3.19.0-18-generic
    npm ERR! argv "/home/azureuser/.nvm/versions/node/v0.12.4/bin/node" "/home/azureuser/.nvm/versions/node/v0.12.4/bin/npm" "install"
    npm ERR! node v0.12.4
    npm ERR! npm  v2.10.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! time@0.11.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the time@0.11.3 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the time package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls time
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/azureuser/chacuatool-news-cron/npm-debug.log

**Comment by paulomcnally** [comment]
Solved!

    sudo apt-get install build-essential
