### ISSUE TITLE
time doesn't compile for ubuntu

### ISSUE THREAD

**Issue by marsinvasion** [TooTallNate/node-time#79]
node-gyp -v
v0.10.10

node -v
v0.12.7

python -V
Python 2.7.6

gcc version 4.8.4

ubuntu 14.04

I get this error everytime I try to compile install time module on ubuntu

/home/dev/workspace/node_modules/time/node_modules/nan/nan.h:233:65: note: in definition of macro 'NanReturnValue'
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                 ^
../src/time.cc:130:69: note: candidate is:
     NanReturnValue(Number::New(static_cast<double>(mktime( &tmstr ))));
                                                                     ^
/home/dev/workspace/node_modules/time/node_modules/nan/nan.h:233:65: note: in definition of macro 'NanReturnValue'
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                 ^
In file included from ../src/time.cc:5:0:
/home/dev/.node-gyp/0.12.7/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/dev/.node-gyp/0.12.7/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/time.cc:7:0:
/home/dev/workspace/node_modules/time/node_modules/nan/nan.h:233:70: error: return-statement with a value, in function returning 'void' [-fpermissive]
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                      ^
../src/time.cc:130:5: note: in expansion of macro 'NanReturnValue'
     NanReturnValue(Number::New(static_cast<double>(mktime( &tmstr ))));
     ^
/home/dev/workspace/node_modules/time/node_modules/nan/nan.h: In instantiation of 'void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]':
/home/dev/workspace/node_modules/time/node_modules/nan/nan.h:592:34:   required from here
/home/dev/workspace/node_modules/time/node_modules/nan/nan.h:311:5: error: 'class v8::Persistent<v8::Object>' has no member named 'Clear'
     handle.Clear();

make: *** [Release/obj.target/time/src/time.o] Error 1
make: Leaving directory `/home/dev/workspace/node_modules/time/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev/workspace/node_modules/time
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-042stab090.5
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "time"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! time@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.10.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

Any idea on what might be going wrong?

**Comment by marsinvasion** [comment]
Downgraded node to v0.10 and it works now.
