### ISSUE TITLE
Install failed on Linux message

### ISSUE THREAD

**Issue by EskenderTamrat** [TooTallNate/node-time#82]
I consistently get the following error message when I tried to install the package with 'node install --save time'. I tried older versions as well.

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.12.7.tar.gz local checksum 173df27d2011f06cdacd097053e11eab075ceb21ec8f2e697d8dceb80e0330e7 not match remote b23d64df051c9c969b0c583f802d5d71de342e53067127a5061415be7e12f39d
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)

gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/time
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.32-573.3.1.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "time"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! time@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.11.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

Thanks.

**Comment by benag** [comment]
Did you solve this one? I have this too

**Comment by game4cesc** [comment]
I don't remember every details (SORRY), but deleting the previously installed packages (by removing the directory containing such files) solved this for me.

**Comment by hijklmno** [comment]
@benag i was able to solve the installation issue on a AWS EC2 instance by running ```yum install gcc-c++ make``` before ```node install --save time```
