### ISSUE TITLE
make failed with exit code: 2

### ISSUE THREAD

**Issue by jazzfog** [TooTallNate/node-time#92]
I tried to install `time` module but this error keeps appearing

`npm install time`

```
> time@0.11.4 install /__SX/node_modules/time
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/__SX/node_modules/time/.node-gyp"
make: Entering directory `/__SX/node_modules/time/build'
  CXX(target) Release/obj.target/time/src/time.o
make: g++: Command not found
make: *** [Release/obj.target/time/src/time.o] Error 127
make: Leaving directory `/__SX/node_modules/time/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/node/bin/node" "/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /__SX/node_modules/time
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/node/bin/node" "/usr/local/bin/npm" "install" "time"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! time@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the time@0.11.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /__SX/npm-debug.log
```

I run it in ubuntu 14.04 vm provisioned by Vagrant.

**Comment by Simone-cogno** [comment]
+1 Same error
