### ISSUE TITLE
CITGM test failing on s390

### ISSUE THREAD

**Issue by GeorgeAdams95** [TooTallNate/node-time#99]
Linux-s390
Node: 6.7.0
npm install -g citgm and then citgm-all

```
35 passing (81ms)
# 1 failing
# 1) exports localtime() should not segfault on a NaN Date value:
# AssertionError: { invalid: true } deepEqual { seconds: 0,
# minutes: 0,
# hours: 0,
# dayOfMonth: 1,
# month: 0,
# year: 70,
# dayOfWeek: 4,
# dayOfYear: 0,
# isDaylightSav
# + expected - actual
# {
# -  "invalid": true
# +  "dayOfMonth": 1
# +  "dayOfWeek": 4
# +  "dayOfYear": 0
# +  "gmtOffset": 0
# +  "hours": 0
# +  "isDaylightSavings": false
# +  "minutes": 0
# +  "month": 0
# +  "seconds": 0
# +  "timezone": "UTC"
# +  "year": 70
# }
# 
# at Context.<anonymous> (test/exports.js:49:14)
# npm ERR! Test failed.  See above for more details.
```

Any help would be apreciated

**Comment by TooTallNate** [comment]
Does the regular `npm test` work?

**Comment by GeorgeAdams95** [comment]
running with npm I can't seem to run npm install in the git hub repo, this is the error I get:
```
 ~/node-time $ npm install

> time@0.11.4 install /home/georgeadams95/node-time
> node-gyp rebuild

make: Entering directory '/home/georgeadams95/node-time/build'
  CXX(target) Release/obj.target/time/src/time.o
In file included from /usr/include/c++/5/utility:68:0,
                 from /home/georgeadams95/.node-gyp/6.7.0/include/node/v8.h:21,
                 from /home/georgeadams95/.node-gyp/6.7.0/include/node/node.h:4,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/time.cc:5:
/usr/include/c++/5/bits/c++config.h:482:29: fatal error: bits/os_defines.h: No such file or directory
compilation terminated.
time.target.mk:90: recipe for target 'Release/obj.target/time/src/time.o' failed
make: *** [Release/obj.target/time/src/time.o] Error 1
make: Leaving directory '/home/georgeadams95/node-time/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/dev/shm/usenode.george/node-v6.7.0-linux-s390/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/dev/shm/usenode.george/node-v6.7.0-linux-s390/bin/node" "/dev/shm/usenode.george/node-v6.7.0-linux-s390/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/georgeadams95/node-time
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/dev/shm/usenode.george/node-v6.7.0-linux-s390/bin/node" "/dev/shm/usenode.george/node-v6.7.0-linux-s390/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! time@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the time@0.11.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/georgeadams95/node-time/npm-debug.log
```
